import { ArrowDownUp, Clock3, LockKeyhole, Sparkles } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import LeagueShell from "@/components/LeagueShell";
import { EmptyLedger, LeagueError, LeagueLoading } from "@/components/LeagueState";
import { Badge } from "@/components/ui/badge";
import { inauguralDraftDays } from "@shared/draft-schedule";
import { trpc } from "@/lib/trpc";

const statusLabel = (status: "PENDING" | "ACTIVE" | "SKIPPED" | "PICKED") => status === "ACTIVE" ? "On clock" : status === "PICKED" ? "Selected" : status === "SKIPPED" ? "Leapfrogged" : "Awaiting pick";

// The public board presents the official three-day schedule before the commissioner posts the randomized order.
export default function DraftBoard() {
  const league = trpc.league.snapshot.useQuery();
  if (league.isLoading) return <LeagueShell><LeagueLoading /></LeagueShell>;
  if (league.error || !league.data) return <LeagueShell><LeagueError message={league.error?.message} /></LeagueShell>;

  const { owners, draftTurns } = league.data;
  const turnByPick = new Map(draftTurns.map(turn => [turn.globalPick, turn]));
  const assignmentById = new Map(owners.flatMap(owner => owner.assignments.map(assignment => [assignment.id, { ...assignment, teamName: owner.teamName }])));
  const orderPublished = draftTurns.length === 216;

  return <LeagueShell eyebrow="2026 inaugural draft"><section className="container pt-10 sm:pt-14">
    <div className="max-w-3xl"><p className="section-kicker">Six rounds · three days · 216 selections</p><h1 className="display-title mt-3">The draft board</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Every program makes two selections per day. Select a day below to follow its two full serpentine rounds, pick by pick.</p></div>
    <div className="mt-8 grid gap-4 md:grid-cols-3"><div className="rule-card"><Sparkles className="h-5 w-5 text-primary" /><div><p className="font-bold">Order announcement</p><p className="mt-1 text-xs leading-5 text-muted-foreground">The official randomized order is announced Sunday, August 23, giving every program advance notice.</p></div></div><div className="rule-card"><Clock3 className="h-5 w-5 text-primary" /><div><p className="font-bold">9:00 AM – 9:00 PM ET</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Each draft day holds 72 selections with a maximum ten-minute selection clock.</p></div></div><div className="rule-card"><LockKeyhole className="h-5 w-5 text-primary" /><div><p className="font-bold">School-group locks</p><p className="mt-1 text-xs leading-5 text-muted-foreground">A school can be selected only once at each roster group across 36 Football.</p></div></div></div>

    <div className="draft-calendar mt-10 p-5 sm:p-6"><p className="section-kicker">Draft calendar</p><div className="mt-4 grid gap-3 md:grid-cols-3">{inauguralDraftDays.map(day => <div key={day.id} className="draft-day-card p-4"><p className="font-condensed text-xs font-bold uppercase tracking-[.14em] text-muted-foreground">Day {day.dayNumber}</p><p className="mt-1 font-display text-lg font-extrabold">{day.weekday}</p><p className="text-sm font-semibold">{day.dateLabel}</p><p className="mt-3 text-xs text-muted-foreground">Rounds {day.rounds[0]} & {day.rounds[1]} · Picks {day.pickRange[0]}–{day.pickRange[1]}</p><p className="mt-1 font-condensed text-sm font-bold tracking-wide text-primary">72 selections · 9 AM–9 PM ET</p></div>)}</div></div>

    <Tabs defaultValue={inauguralDraftDays[0]?.id} className="mt-10"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="section-kicker">Daily boards</p><h2 className="mt-2 font-display text-2xl font-extrabold tracking-tight">Three days. Two rounds each.</h2></div><Badge variant={orderPublished ? "secondary" : "outline"}>{orderPublished ? "Official order posted" : "Order pending Sunday, Aug 23"}</Badge></div><TabsList className="mt-5 h-auto w-full justify-start gap-1 overflow-x-auto rounded-xl border border-border bg-card p-1">{inauguralDraftDays.map(day => <TabsTrigger key={day.id} value={day.id} className="min-w-36">Day {day.dayNumber} · R{day.rounds[0]}–{day.rounds[1]}</TabsTrigger>)}</TabsList>
      {inauguralDraftDays.map(day => <TabsContent key={day.id} value={day.id} className="mt-6"><div className="draft-calendar p-5 sm:p-6"><div className="flex flex-col justify-between gap-3 border-b border-border pb-5 sm:flex-row sm:items-end"><div><p className="section-kicker">Day {day.dayNumber} · {day.weekday}</p><h3 className="mt-2 font-display text-2xl font-extrabold tracking-tight">{day.dateLabel}</h3><p className="mt-1 text-sm text-muted-foreground">Rounds {day.rounds[0]} and {day.rounds[1]} · {day.pickRange[0]}–{day.pickRange[1]} · 72 selections</p></div><div className="flex items-center gap-2 font-condensed text-base font-bold tracking-wide text-primary"><ArrowDownUp className="h-4 w-4" /> 9:00 AM–9:00 PM ET</div></div><div className="mt-6 grid gap-6 xl:grid-cols-2">{day.rounds.map(roundNumber => { const firstPick = (roundNumber - 1) * 36 + 1; const lastPick = firstPick + 35; return <section key={roundNumber} className="draft-round overflow-hidden"><div className="draft-round-header flex items-center justify-between border-b border-border px-4 py-3"><div><p className="font-display text-lg font-extrabold">Round {roundNumber}</p><p className="text-xs text-muted-foreground">Picks {firstPick}–{lastPick} · {roundNumber % 2 ? "1 → 36" : "36 → 1"}</p></div><Badge variant="outline">36 picks</Badge></div><div className="divide-y divide-border/70">{Array.from({ length: 36 }, (_, index) => { const globalPick = firstPick + index; const turn = turnByPick.get(globalPick); const assignment = turn?.draftSlotId ? assignmentById.get(turn.draftSlotId) : undefined; return <div key={globalPick} className="grid grid-cols-[42px_minmax(0,1fr)_auto] items-center gap-3 px-4 py-3"><span className="font-display text-base font-extrabold text-primary">{globalPick}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{turn?.teamName ?? "Draft order pending"}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{assignment?.schoolName ? `${assignment.schoolName} · ${assignment.position === "K_ST" ? "K/ST" : assignment.position}` : orderPublished ? statusLabel(turn?.status ?? "PENDING") : "Official order announced Sunday, Aug 23"}</p></div><Badge variant={turn?.status === "ACTIVE" ? "default" : "outline"} className="justify-self-end text-[10px]">{turn ? statusLabel(turn.status) : "Pending"}</Badge></div>})}</div></section> })}</div></div></TabsContent>)}</Tabs>
  </section></LeagueShell>;
}
