import { LockKeyhole, CircleCheck, CircleDashed } from "lucide-react";
import LeagueShell from "@/components/LeagueShell";
import { EmptyLedger, LeagueError, LeagueLoading } from "@/components/LeagueState";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";

const slots = ["QB", "RB", "WR", "TE", "K_ST", "DEF"] as const;
const name = (position: string) => position === "K_ST" ? "K/ST" : position;

export default function DraftBoard() {
  const league = trpc.league.snapshot.useQuery();
  if (league.isLoading) return <LeagueShell><LeagueLoading /></LeagueShell>;
  if (league.error || !league.data) return <LeagueShell><LeagueError message={league.error?.message} /></LeagueShell>;
  const { owners } = league.data;
  return <LeagueShell eyebrow="Live serpentine draft"><section className="container pt-10 sm:pt-14"><div className="max-w-3xl"><p className="section-kicker">Six rounds · three days · 216 selections</p><h1 className="display-title mt-3">The draft board</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">The inaugural order runs forward in rounds 1, 3, and 5, then reverses in rounds 2, 4, and 6. A missed ten-minute pick leapfrogs without stopping the board.</p></div><div className="mt-8 grid gap-4 md:grid-cols-2"><div className="rule-card"><CircleCheck className="h-5 w-5 text-primary" /><div><p className="font-bold">Serpentine order enforced</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Every program receives one turn per round in the published 1–36 / 36–1 order.</p></div></div><div className="rule-card"><LockKeyhole className="h-5 w-5 text-primary" /><div><p className="font-bold">Group locks enforced</p><p className="mt-1 text-xs leading-5 text-muted-foreground">One school can be selected only once at each roster group across 36 Football.</p></div></div></div>
    {owners.length ? <div className="mt-10 space-y-9">{slots.map(position => { const picks = owners.flatMap(owner => owner.picks.filter(pick => pick.position === position).map(pick => ({ ...pick, teamName: owner.teamName, ownerName: owner.displayName, assignment: owner.assignments.find(item => item.position === position) }))).sort((a, b) => a.draftPosition - b.draftPosition); return <section key={position}><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-2xl font-extrabold tracking-tight">{name(position)}</h2><Badge variant="secondary">{picks.length}/36 selected</Badge></div><div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="grid grid-cols-[70px_minmax(0,1fr)_minmax(0,1fr)] gap-3 border-b border-border bg-accent/50 px-4 py-3 text-[10px] font-extrabold uppercase tracking-[0.16em] text-muted-foreground sm:px-6"><span>Pick</span><span>School group</span><span>Program</span></div>{picks.length ? picks.map(pick => <div key={pick.id} className="grid grid-cols-[70px_minmax(0,1fr)_minmax(0,1fr)] items-center gap-3 border-b border-border/70 px-4 py-4 last:border-0 sm:px-6"><span className="font-display text-lg font-extrabold text-primary">{pick.draftPosition}</span><div className="min-w-0"><p className="truncate font-bold">{pick.schoolName}</p><p className="mt-0.5 text-xs text-muted-foreground">{name(position)} group</p></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{pick.teamName}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{pick.ownerName}</p></div></div>) : <div className="p-6"><EmptyLedger title={`No ${name(position)} groups selected`} detail="Selections appear here as programs make their turns." /></div>}</div></section> })}</div> : <div className="mt-10"><EmptyLedger title="The board is awaiting its 36 programs" detail="Once conferences, programs, and the randomized serpentine order are in place, owner selections update here automatically." /></div>}
  </section></LeagueShell>;
}
