import { useEffect, useState } from "react";
import { Camera, KeyRound, LockKeyhole, Palette, Save, ShieldCheck, UserRound } from "lucide-react";
import LeagueShell from "@/components/LeagueShell";
import { EmptyLedger, LeagueError, LeagueLoading } from "@/components/LeagueState";
import { OwnerSignInForm } from "@/components/OwnerSignInForm";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

type ProfileForm = {
  displayName: string; teamName: string; nickname: string; programIdentity: string; inspiration: string; primaryColor: string; accentColor: string; brandingNotes: string; rivalryPreference: string; email: string; phone: string; currentPin: string; newPin: string; logoDataUrl: string | null;
};

const emptyForm: ProfileForm = { displayName: "", teamName: "", nickname: "", programIdentity: "", inspiration: "", primaryColor: "#8A5A2B", accentColor: "#17120E", brandingNotes: "", rivalryPreference: "", email: "", phone: "", currentPin: "", newPin: "", logoDataUrl: null };

function fieldValue(value: string | null | undefined) { return value ?? ""; }

export default function MyTeam() {
  const { user, loading, isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const profile = trpc.league.myProfile.useQuery(undefined, { enabled: isAuthenticated });
  const [form, setForm] = useState<ProfileForm>(emptyForm);
  const [logoPreview, setLogoPreview] = useState<string | null>(null);
  const update = trpc.league.updateMyProfile.useMutation({
    onSuccess: result => {
      toast.success(result?.emailChanged ? "Your sign-in email was changed and your session was renewed." : "Your team profile has been saved.");
      setForm(current => ({ ...current, currentPin: "", newPin: "", logoDataUrl: null }));
      utils.auth.me.invalidate(); utils.league.myProfile.invalidate(); utils.league.snapshot.invalidate(); utils.league.myDraft.invalidate();
    },
    onError: error => toast.error(error.message),
  });

  useEffect(() => {
    const registration = profile.data?.registration;
    if (!registration) return;
    setForm({ displayName: registration.displayName, teamName: registration.teamName, nickname: fieldValue(registration.nickname), programIdentity: fieldValue(registration.programIdentity), inspiration: fieldValue(registration.inspiration), primaryColor: fieldValue(registration.primaryColor) || "#8A5A2B", accentColor: fieldValue(registration.accentColor) || "#17120E", brandingNotes: fieldValue(registration.brandingNotes), rivalryPreference: fieldValue(registration.rivalryPreference), email: registration.email, phone: registration.phone, currentPin: "", newPin: "", logoDataUrl: null });
    setLogoPreview(registration.logoUrl);
  }, [profile.data]);

  const set = <Key extends keyof ProfileForm>(key: Key, value: ProfileForm[Key]) => setForm(current => ({ ...current, [key]: value }));
  const readLogo = (file: File | undefined) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => { const dataUrl = typeof reader.result === "string" ? reader.result : null; set("logoDataUrl", dataUrl); setLogoPreview(dataUrl); };
    reader.readAsDataURL(file);
  };

  if (loading) return <LeagueShell><LeagueLoading /></LeagueShell>;
  if (!isAuthenticated) return <LeagueShell eyebrow="My team"><section className="container py-14 sm:py-20"><div className="mx-auto max-w-2xl rounded-3xl border border-border bg-card p-8 shadow-sm"><LockKeyhole className="mx-auto h-7 w-7 text-primary" /><p className="section-kicker mt-5 text-center">Program owners</p><h1 className="mt-3 text-center font-display text-4xl font-extrabold tracking-tight">Welcome back.</h1><p className="mx-auto mt-4 max-w-lg text-center text-sm leading-7 text-muted-foreground">Sign in with the email and PIN from your approved 36 Football program to manage your team settings.</p><OwnerSignInForm /></div></section></LeagueShell>;
  if (profile.isLoading) return <LeagueShell><LeagueLoading /></LeagueShell>;
  if (profile.error || !profile.data) return <LeagueShell><LeagueError message={profile.error?.message} /></LeagueShell>;
  if (!profile.data.owner) return <LeagueShell eyebrow="My team"><section className="container py-14"><EmptyLedger title="Your program is not linked yet" detail="Your registration is approved, but the commissioner has not assigned it to one of the 36 program slots yet." /></section></LeagueShell>;
  const registration = profile.data.registration;

  return <LeagueShell eyebrow="My team"><section className="container py-9 sm:py-12"><header className="flex flex-col gap-6 border-b border-border pb-8 md:flex-row md:items-end md:justify-between"><div className="flex min-w-0 items-center gap-5"><div className="flex h-20 w-20 shrink-0 items-center justify-center overflow-hidden rounded-2xl border border-border bg-accent/50">{logoPreview ? <img src={logoPreview} alt={`${form.teamName} logo`} className="h-full w-full object-cover" /> : <span className="font-display text-3xl font-extrabold text-primary">{form.teamName.slice(0, 1)}</span>}</div><div><p className="section-kicker">Owner profile</p><h1 className="display-title mt-2">{form.teamName || "Your program"}</h1><p className="mt-2 text-sm text-muted-foreground">Manage your program identity, contact number, team logo, colors, sign-in email, and PIN from one private place.</p></div></div><div className="rounded-2xl border border-primary/15 bg-primary/5 px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">Account email</p><p className="mt-1 text-sm font-bold">{registration.email}</p><p className="mt-1 text-xs text-muted-foreground">Verified email changes renew your secure session.</p></div></header>
    <form className="mt-8 grid gap-6 xl:grid-cols-[1fr_1fr]" onSubmit={event => { event.preventDefault(); update.mutate({ displayName: form.displayName, teamName: form.teamName, nickname: form.nickname || null, programIdentity: form.programIdentity || null, inspiration: form.inspiration || null, primaryColor: form.primaryColor || null, accentColor: form.accentColor || null, brandingNotes: form.brandingNotes || null, rivalryPreference: form.rivalryPreference || null, email: form.email, phone: form.phone, currentPin: form.currentPin || null, newPin: form.newPin || null, logoDataUrl: form.logoDataUrl }); }}>
      <section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-start gap-3"><Palette className="mt-0.5 h-5 w-5 text-primary" /><div><p className="section-kicker">Program identity</p><h2 className="mt-2 font-display text-2xl font-extrabold">Build your school</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">These details shape the public identity of your 36 Football program.</p></div></div><div className="mt-6 grid gap-4"><div className="grid gap-2"><Label htmlFor="team-name">Program name</Label><Input id="team-name" value={form.teamName} onChange={event => set("teamName", event.target.value)} required /></div><div className="grid gap-2"><Label htmlFor="nickname">Team nickname</Label><Input id="nickname" value={form.nickname} onChange={event => set("nickname", event.target.value)} placeholder="The Night Owls" /></div><div className="grid gap-2"><Label htmlFor="identity">Program identity</Label><Input id="identity" value={form.programIdentity} onChange={event => set("programIdentity", event.target.value)} placeholder="Mascot, character, or tradition" /></div><div className="grid gap-2"><Label htmlFor="inspiration">School inspiration</Label><Input id="inspiration" value={form.inspiration} onChange={event => set("inspiration", event.target.value)} placeholder="Hometown, landmark, inside joke, or fiction" /></div><div className="grid gap-2"><Label htmlFor="rivalry">Rivalry preference</Label><Input id="rivalry" value={form.rivalryPreference} onChange={event => set("rivalryPreference", event.target.value)} placeholder="A future rival program or theme" /></div><div className="grid gap-2"><Label htmlFor="notes">Branding notes</Label><Textarea id="notes" value={form.brandingNotes} onChange={event => set("brandingNotes", event.target.value)} placeholder="A few words about the look and personality of your program." rows={4} /></div></div></section>
      <section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-start gap-3"><UserRound className="mt-0.5 h-5 w-5 text-primary" /><div><p className="section-kicker">Owner & access</p><h2 className="mt-2 font-display text-2xl font-extrabold">Your private settings</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Your email is your sign-in identity. Your phone remains private to the commissioner and is never shown publicly.</p></div></div><div className="mt-6 grid gap-4"><div className="grid gap-2"><Label htmlFor="owner-name">Owner name</Label><Input id="owner-name" value={form.displayName} onChange={event => set("displayName", event.target.value)} required /></div><div className="grid gap-2"><Label htmlFor="phone">Phone number</Label><Input id="phone" type="tel" value={form.phone} onChange={event => set("phone", event.target.value)} required /></div><div className="grid gap-2"><Label htmlFor="email">Sign-in email</Label><Input id="email" type="email" value={form.email} onChange={event => set("email", event.target.value)} required autoComplete="email" /><p className="text-xs leading-5 text-muted-foreground">Changing email requires your current PIN and immediately renews your secure owner session.</p></div><div className="rounded-xl border border-border bg-accent/30 p-4"><div className="flex items-center gap-2"><KeyRound className="h-4 w-4 text-primary" /><p className="text-sm font-bold">Change credentials <span className="font-normal text-muted-foreground">(optional)</span></p></div><p className="mt-2 text-xs leading-5 text-muted-foreground">Enter your current PIN to save a changed sign-in email or choose a new PIN.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="current-pin">Current PIN</Label><Input id="current-pin" type="password" inputMode="numeric" value={form.currentPin} onChange={event => set("currentPin", event.target.value)} autoComplete="current-password" placeholder="Required to change" /></div><div className="grid gap-2"><Label htmlFor="new-pin">New PIN</Label><Input id="new-pin" type="password" inputMode="numeric" value={form.newPin} onChange={event => set("newPin", event.target.value)} autoComplete="new-password" placeholder="4–12 digits" /></div></div></div></div></section>
      <section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6 xl:col-span-2"><div className="grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><div><p className="section-kicker">Colors & crest</p><h2 className="mt-2 font-display text-2xl font-extrabold">Make it yours.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Choose colors and upload a PNG, JPEG, or WebP logo. The logo must be 1.5 MB or smaller.</p><div className="mt-5 flex items-center gap-4"><div className="flex h-20 w-20 items-center justify-center overflow-hidden rounded-2xl border border-border" style={{ backgroundColor: form.primaryColor }}>{logoPreview ? <img src={logoPreview} alt="Current team logo" className="h-full w-full object-cover" /> : <Camera className="h-6 w-6" style={{ color: form.accentColor }} />}</div><div className="grid gap-2"><Label htmlFor="team-logo">Team logo</Label><Input id="team-logo" type="file" accept="image/png,image/jpeg,image/webp" onChange={event => readLogo(event.target.files?.[0])} /><p className="text-xs text-muted-foreground">A new file replaces the current logo after you save.</p></div></div></div><div className="grid content-start gap-4 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="primary-color">Primary color</Label><div className="flex gap-2"><Input id="primary-color" type="color" value={form.primaryColor} onChange={event => set("primaryColor", event.target.value)} className="h-10 w-14 p-1" /><Input value={form.primaryColor} onChange={event => set("primaryColor", event.target.value.toUpperCase())} pattern="^#[0-9A-Fa-f]{6}$" /></div></div><div className="grid gap-2"><Label htmlFor="accent-color">Accent color</Label><div className="flex gap-2"><Input id="accent-color" type="color" value={form.accentColor} onChange={event => set("accentColor", event.target.value)} className="h-10 w-14 p-1" /><Input value={form.accentColor} onChange={event => set("accentColor", event.target.value.toUpperCase())} pattern="^#[0-9A-Fa-f]{6}$" /></div></div><div className="sm:col-span-2 rounded-xl border border-border p-5" style={{ background: `linear-gradient(135deg, ${form.primaryColor} 0%, ${form.primaryColor} 62%, ${form.accentColor} 62%, ${form.accentColor} 100%)` }}><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/70">Program palette</p><p className="mt-2 font-display text-2xl font-extrabold text-white">{form.teamName || "Your program"}</p></div></div></div><div className="mt-7 flex flex-col-reverse gap-3 border-t border-border pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 text-primary" /> Changes are saved only to your assigned program.</p><Button type="submit" disabled={update.isPending} className="sm:min-w-44"><Save className="mr-2 h-4 w-4" /> {update.isPending ? "Saving profile…" : "Save team settings"}</Button></div></section>
    </form></section></LeagueShell>;
}
